apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  managedBy: "platform-team"
  environment: "dev"
bases:
  - ../../../apps/webapp
replicas:
  - name: web-app
    count: 1
#namePrefix: dev-